### ISSUE TITLE
BZ uses 1 MyISAM table - This is a problem if we want to migrate to Aurora

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla#10]
For several reasons, we would like to use AWS Aurora as the DB engine for the BZFE.

See https://github.com/unee-t/bz-database/issues/8, 
issue #9 
and https://github.com/unee-t/frontend/issues/13

We need to understand how we can have the table 'bugs_fulltext' converted from MyISAM to INNODb AND make sure that the BZ checksetup.pl script is NOT reverting the changes back each time it's run

**Comment by franck-boullier** [comment]
People have tried to do this already BTW https://bugzilla.mozilla.org/show_bug.cgi?id=981487
So there seem to be a path there...

**Comment by franck-boullier** [comment]
The changes that we need vs the BZ vanilla code are documented there:
https://github.com/mozilla-bteam/bmo/commit/d247ef1
@kaihendry how can we make sure that we make these changes persistent in the docker build we use?

**Comment by kaihendry** [comment]
"docker build", you mean local development? 

You would need to update:
https://github.com/unee-t/bugzilla-customisation/blob/master/sql/demo.sql.gz

```
[hendry@t480s sql]$ zgrep -i myisam demo.sql.gz
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by franck-boullier** [comment]
"You would need to update:
https://github.com/unee-t/bugzilla-customisation/blob/master/sql/demo.sql.gz"

Not only: We also need to update the files as they did here https://github.com/mozilla-bteam/bmo/commit/d247ef1
This is because BZ runs some sanity checks on a regular basis and we need to have these recorded so that there is consistency
