### ISSUE TITLE
mariadb:latest doesn't work with innodb patch

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla#12]
https://github.com/bugzilla/bugzilla/pull/62/commits/ea2b640afd588f72529fa9dfd6d212be415d0c5f
https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml#L29
https://bugzilla.mozilla.org/show_bug.cgi?id=1467006
https://github.com/docker-library/mariadb/issues/174

**Comment by franck-boullier** [comment]
Dang...
I guess the temporary fix is to us the previous version of BZ until this is solved right?

**Comment by kaihendry** [comment]
Nah, only https://hub.docker.com/_/mariadb/ is the issue I feel. It doesn't bother us yet with Aurora since its version strings don't appear to choke the check.
