### ISSUE TITLE
Need to be able to update the favicon

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla#2]
The favicon is located in the folder
/images
We need to include this in the customization as this needs to be changed from a vanilla BZ installation too.

**Comment by kaihendry** [comment]
In your template add something like:

    <link rel="icon" type="image/png" href="https://s.natalian.org/2017-10-18/so-square.PNG" />

Instead of https://github.com/unee-t/bugzilla/blob/master/custom/global/header.html.tmpl#L218

**Comment by franck-boullier** [comment]
Perfect, that's a better solution!

**Comment by kaihendry** [comment]
https://github.com/unee-t/bugzilla/commit/cef8237ca252c14b22ec54e2390d56bf15fd0c3e

**Comment by franck-boullier** [comment]
This works
