### ISSUE TITLE
Generate random passwords

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla#4]
When we do an installation with dockers, the cat .env variable are the same each time.

It would be nice to be able to generate the passwords randomly.
To access the passwords we can always do 
cat .env
To get the password variables for the environment we just built

**Comment by kaihendry** [comment]
For the dev environment, the password can be static.

For production, users should already have their emails set by themselves in advance?

**Comment by franck-boullier** [comment]
"For production, users should already have their emails set by themselves in advance?"
That is correct but I'm talking about the root and DB password here: the credential to log into the application back-end and DB...
If I deploy this in a prod envo I need to change the passwords for the database which is not optimal

I am not talking about the BZFE user password

**Comment by kaihendry** [comment]
Sorry, I initially misunderstood.

I will store secrets in https://ap-southeast-1.console.aws.amazon.com/ec2/v2/home?region=ap-southeast-1#Parameters:sort=Name and document how do that.

**Comment by kaihendry** [comment]
Check out how it works now https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env
