### ISSUE TITLE
Make up fails with error - make: *** No rule to make target 'up'

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla#6]
What I did:
- Create a new fresh AWS instance (Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-6f198a0c)
- install dockers
sudo apt install docker.io
- install docker compose
sudo apt install docker-compose
- Install make:
sudo apt-get install make
- Configure docker:
sudo usermod -aG docker $USER
sudo systemctl start docker
- Log out and log back in
- check that all is OK:
docker ps
No error there
- Clone the latest repo
git clone https://github.com/unee-t/bugzilla.git
- Move to the bz folder
cd ~/bugzilla
- Try to build it
make up

This does not work as intended
Error message:
---
ubuntu@ip-172-31-20-119:~/bugzilla$ make up
make: *** No rule to make target 'up'.  Stop.
---

Did I do anything wrong?
Any idea how to fix that?

**Comment by kaihendry** [comment]
Clone bugzilla-customisation instead

**Comment by franck-boullier** [comment]
OK error disappear when I clone https://github.com/unee-t/bugzilla-customisation.git instead
